<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\User;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::role('owner')->first();
        $agency = User::role('agency')->first();
        $villaAngelaCityId = DB::table('cities')->where('name', 'Villa Ángela')->first()->city_id;
        $neighborhoods = DB::table('neighborhoods')
            ->join('cities', 'neighborhoods.city_id', '=', 'cities.city_id')
            ->where('cities.name', 'Villa Ángela')
            ->pluck('neighborhoods.neighborhood_id', 'neighborhoods.name');

        // 10 Propiedades de ejemplo
        $properties = [
            [
                'property_type' => 'apartment',
                'title' => 'Departamento luminoso en el centro',
                'description' => 'Hermoso departamento de 2 ambientes en pleno centro de Villa Ángela, muy luminoso y con excelente ubicación.',
                'address' => 'Av. San Martín 1234',
                'neighborhood' => 'Centro',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'rooms' => 3,
                'covered_m2' => 65.50,
                'total_m2' => 65.50,
                'has_patio' => false,
                'has_garage' => false,
                'amenities' => json_encode(['aire_acondicionado', 'balcon', 'cocina_equipada']),
                'operation' => 'rent',
                'price' => 85000,
                'conditions' => 'No fumadores. Expensas incluidas.',
                'allows_pets' => false,
                'allows_children' => true,
                'publisher' => 'owner',
            ],
            [
                'property_type' => 'house',
                'title' => 'Casa familiar con patio y parrilla',
                'description' => 'Amplia casa familiar de 3 dormitorios con gran patio, parrilla y garage. Ideal para familias.',
                'address' => 'Calle Belgrano 567',
                'neighborhood' => 'Barrio Norte',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'rooms' => 5,
                'covered_m2' => 120.00,
                'total_m2' => 200.00,
                'has_patio' => true,
                'has_garage' => true,
                'amenities' => json_encode(['garage', 'patio', 'parrilla', 'aire_acondicionado']),
                'operation' => 'sale',
                'price' => 15000000,
                'conditions' => 'Financiación disponible. Escritura lista.',
                'allows_pets' => true,
                'allows_children' => true,
                'publisher' => 'agency',
            ],
            [
                'property_type' => 'apartment',
                'title' => 'Monoambiente amoblado',
                'description' => 'Acogedor monoambiente completamente amoblado, listo para habitar. Incluye todos los servicios.',
                'address' => 'Calle Sarmiento 890',
                'neighborhood' => 'Centro',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'rooms' => 2,
                'covered_m2' => 45.00,
                'total_m2' => 45.00,
                'has_patio' => false,
                'has_garage' => false,
                'amenities' => json_encode(['aire_acondicionado', 'amoblado']),
                'operation' => 'rent',
                'price' => 65000,
                'conditions' => 'Solo personas solas o parejas. Todos los servicios incluidos.',
                'allows_pets' => false,
                'allows_children' => false,
                'publisher' => 'owner',
            ],
            [
                'property_type' => 'house',
                'title' => 'Casa premium con piscina',
                'description' => 'Exclusiva casa de 4 dormitorios con piscina, quincho y amplio jardín. La mejor zona de Villa Progreso.',
                'address' => 'Av. Libertad 445',
                'neighborhood' => 'Villa Progreso',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'rooms' => 6,
                'covered_m2' => 180.00,
                'total_m2' => 350.00,
                'has_patio' => true,
                'has_garage' => true,
                'amenities' => json_encode(['garage', 'piscina', 'quincho', 'aire_acondicionado']),
                'operation' => 'sale',
                'price' => 25000000,
                'conditions' => 'Venta directa. Acepta permuta por menor valor.',
                'allows_pets' => true,
                'allows_children' => true,
                'publisher' => 'agency',
            ],
            [
                'property_type' => 'apartment',
                'title' => 'Departamento con balcón al frente',
                'description' => '2 ambientes con balcón al frente, cocina equipada y lavarropas. Muy buena ubicación.',
                'address' => 'Calle Mitre 223',
                'neighborhood' => 'Barrio Sur',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'rooms' => 3,
                'covered_m2' => 70.00,
                'total_m2' => 70.00,
                'has_patio' => false,
                'has_garage' => false,
                'amenities' => json_encode(['balcon', 'cocina_equipada', 'lavarropas']),
                'operation' => 'rent',
                'price' => 75000,
                'conditions' => 'Garantía propietaria excluyente.',
                'allows_pets' => true,
                'allows_children' => true,
                'publisher' => 'owner',
            ],
            [
                'property_type' => 'commercial',
                'title' => 'Local comercial sobre avenida principal',
                'description' => 'Amplio local comercial con vidriera sobre Av. San Martín. Ideal para cualquier rubro comercial.',
                'address' => 'Av. Principal 100',
                'neighborhood' => 'Centro',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'rooms' => 3,
                'covered_m2' => 90.00,
                'total_m2' => 90.00,
                'has_patio' => false,
                'has_garage' => false,
                'amenities' => json_encode(['aire_acondicionado', 'vidriera', 'deposito']),
                'operation' => 'rent',
                'price' => 120000,
                'conditions' => 'Contratos mínimo 2 años. Garantía comercial.',
                'allows_pets' => false,
                'allows_children' => false,
                'publisher' => 'agency',
            ],
            [
                'property_type' => 'house',
                'title' => 'Casa con garage y parrilla',
                'description' => 'Casa de 2 dormitorios con garage techado, patio con parrilla y buen estado general.',
                'address' => 'Calle Moreno 778',
                'neighborhood' => 'Barrio Obrero',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'rooms' => 4,
                'covered_m2' => 85.00,
                'total_m2' => 150.00,
                'has_patio' => true,
                'has_garage' => true,
                'amenities' => json_encode(['patio', 'garage', 'parrilla']),
                'operation' => 'rent',
                'price' => 70000,
                'conditions' => 'Se admiten mascotas pequeñas.',
                'allows_pets' => true,
                'allows_children' => true,
                'publisher' => 'owner',
            ],
            [
                'property_type' => 'apartment',
                'title' => 'Departamento en edificio con amenities',
                'description' => '3 ambientes en moderno edificio con SUM, ascensor y portero. Excelente calidad constructiva.',
                'address' => 'Av. Independencia 556',
                'neighborhood' => 'Villa Nueva',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'rooms' => 4,
                'covered_m2' => 95.00,
                'total_m2' => 95.00,
                'has_patio' => false,
                'has_garage' => true,
                'amenities' => json_encode(['aire_acondicionado', 'balcon', 'sum', 'ascensor']),
                'operation' => 'sale',
                'price' => 12000000,
                'conditions' => 'Apto crédito hipotecario. Cochera incluida.',
                'allows_pets' => false,
                'allows_children' => true,
                'publisher' => 'agency',
            ],
            [
                'property_type' => 'house',
                'title' => 'Casa con quincho y amplio patio',
                'description' => 'Hermosa casa de 3 dormitorios con quincho techado, amplio patio y muy buena orientación.',
                'address' => 'Calle Rivadavia 334',
                'neighborhood' => 'Villa Esperanza',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'rooms' => 5,
                'covered_m2' => 110.00,
                'total_m2' => 220.00,
                'has_patio' => true,
                'has_garage' => true,
                'amenities' => json_encode(['garage', 'patio', 'quincho', 'aire_acondicionado']),
                'operation' => 'rent',
                'price' => 95000,
                'conditions' => 'Inmueble en excelente estado. Referencias comerciales.',
                'allows_pets' => true,
                'allows_children' => true,
                'publisher' => 'owner',
            ],
            [
                'property_type' => 'commercial',
                'title' => 'Galpón industrial con oficinas',
                'description' => 'Amplio galpón de 150m2 con oficina y baño. Ideal para depósito o actividad industrial liviana.',
                'address' => 'Av. San Martín 889',
                'neighborhood' => 'Barrio Industrial',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'rooms' => 2,
                'covered_m2' => 150.00,
                'total_m2' => 150.00,
                'has_patio' => true,
                'has_garage' => false,
                'amenities' => json_encode(['deposito', 'carga_descarga', 'oficina']),
                'operation' => 'rent',
                'price' => 180000,
                'conditions' => 'Para uso comercial o industrial. Documentación al día.',
                'allows_pets' => false,
                'allows_children' => false,
                'publisher' => 'agency',
            ],
        ];

        foreach ($properties as $property) {
            $propertyId = Str::uuid();
            $publisherUser = $property['publisher'] === 'owner' ? $owner : $agency;
            
            DB::table('properties')->insert([
                'property_id' => $propertyId,
                'owner_id' => $owner->id,
                'city_id' => $villaAngelaCityId,
                'neighborhood_id' => $neighborhoods[$property['neighborhood']] ?? null,
                'property_type' => $property['property_type'],
                'title' => $property['title'],
                'description' => $property['description'],
                'address' => $property['address'],
                'bedrooms' => $property['bedrooms'],
                'bathrooms' => $property['bathrooms'],
                'rooms' => $property['rooms'],
                'covered_m2' => $property['covered_m2'],
                'total_m2' => $property['total_m2'],
                'latitude' => $property['latitude'] ?? null,
                'longitude' => $property['longitude'] ?? null,
                'formatted_address' => $property['address'] . ', Villa Ángela, Chaco',
                'location_precision' => 4,
                'map_url' => $property['map_url'] ?? null,
                'has_patio' => $property['has_patio'] ?? false,
                'has_garage' => $property['has_garage'] ?? false,
                'amenities' => $property['amenities'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Crear listing para cada propiedad
            DB::table('listings')->insert([
                'listing_id' => Str::uuid(),
                'property_id' => $propertyId,
                'publisher_id' => $publisherUser->id,
                'operation_type' => $property['operation'],
                'price' => $property['price'],
                'currency' => 'ARS',
                'availability_status' => 'available',
                'moderation_status' => 'approved',
                'requirements' => $property['operation'] === 'rent' 
                    ? 'Recibo de sueldo, garantía propietaria' 
                    : 'Documentación completa, seña del 30%',
                'conditions' => $property['conditions'] ?? null,
                'allows_pets' => $property['allows_pets'] ?? false,
                'allows_children' => $property['allows_children'] ?? true,
                'available_from' => now()->addDays(rand(1, 30)),
                'allow_messages' => true,
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}