version: '3.8'

services:
  buprop-db:
    image: postgres:15-alpine
    container_name: buprop-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: buprop
      POSTGRES_USER: buprop_user
      POSTGRES_PASSWORD: buprop_pass
    volumes:
      - buprop-db-data:/var/lib/postgresql/data
    networks:
      - buprop-network

  buprop-redis:
    image: redis:7-alpine
    container_name: buprop-redis
    ports:
      - "6380:6379"
    networks:
      - buprop-network

volumes:
  buprop-db-data:

networks:
  buprop-network:
    driver: bridge